name: Pixel Hunter Daily Report

on:
  schedule:
    - cron: '0 2 * * *' # 09:00 AM UTC+7
  workflow_dispatch:

jobs:
  hunt:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # Đã cập nhật lên 3.11 để fix lỗi thư viện

      - name: Install dependencies
        # Xóa các phiên bản cứng trong requirements.txt để tránh lỗi
        run: pip install -r requirements.txt

      - name: Run Scraper
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py

      - name: Commit Price History
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update: daily price report"
          # QUAN TRỌNG: Đổi thành dấu chấm (.) để lưu TẤT CẢ file thay đổi
          file_pattern: .